@CleanArchDemo.Presentation_HostAddress = https://localhost:7215

### تست ساده
GET {{CleanArchDemo.Presentation_HostAddress}}/api/test

### گرفتن مشتری محصولات
GET {{CleanArchDemo.Presentation_HostAddress}}/api/customer

### ایجاد مشتری جدید
POST {{CleanArchDemo.Presentation_HostAddress}}/api/customer
Content-Type: application/json

{
  "name": "Hassan",
  "email": "hassan@example.com",
  "street": "Main St",
  "city": "Belgrade",
  "postalCode": "11000"
}


### گرفتن لیست محصولات
GET {{CleanArchDemo.Presentation_HostAddress}}/api/product

### ثبت محصولات جدید
POST {{CleanArchDemo.Presentation_HostAddress}}/api/product
Content-Type: application/json

{
  "name": "Oil",
  "price": {
    "amount": 1000,
    "currency": "ريال"
  }
}


### ثبت سفارش جدید
POST {{CleanArchDemo.Presentation_HostAddress}}/api/order
Content-Type: application/json

{
  "customerId": 1,
  "items": [
    { "productId": 1, "quantity": 2 },
    { "productId": 2, "quantity": 1 }
  ]
}

### گرفتن سفارش با شناسه
GET {{CleanArchDemo.Presentation_HostAddress}}/api/order/1